name: My First Workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: welcome page message
          run: sudo echo "welcome to my first github action"

        - name: create directory
          run: sudo mkdir workshops

        - name: create a file in derectory
          run: sudo touch test.txt

        - name: update runner
          run: sudo apt update -y

        - name: docker installation
          run: sudo apt install docker.io -y
