name: My First Workflow

on: push

jobs:
    first_jobs:
        runs-on: ubuntu-latest
        steps:
        - name: welcome page message
          run: echo "welcome to my first github action"

        - name: create directory
          run: mkdir workshops

        - name: create a file in derectory
          run: touch test.txt

        - name: update runner
          run: apt update -y
